kind: pipeline
type: docker
name: greeting

platform:
  os: linux
  arch: amd64

clone:
  disable: true

steps:
- name: en
  image: alpine
  commands:
  - echo hello world

- name: fr
  image: alpine
  commands:
  - echo bonjour monde
